export default {
  name: 'English',
  translation: {
    mainPage: 'Main page',
    graphiql: 'Graphiql',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    variables: 'Variables',
    headers: 'Headers',
    PleaseEnterName: 'Please enter name',
    FullName: 'Full Name',
    EmailAddress: 'E-mail Address',
    Password: 'Password',
    Register: 'Register',
    AlreadyHaveAnAccount: 'Already have an account?',
    Login: 'Login',
    SendPasswordResetEmail: 'Send password reset email',
    DontHave: 'Don`t have an account?',
    ForgotPassword: 'Forgot Password',
    ItsShort: 'It is too short',
    ItEmpty: 'It can`t be empty',
    ItEmail: 'It isn`t E-mail',
    longer: 'The password must be 8 or more characters long',
    NeedCapital: 'Need at least one capital letter',
    NeedSpecial: 'The password must contain numbers and a special character',
    NotRegister: 'This e-mail is`n register yet',
    CheckEOrP: 'Check e-mail or password',
    logOut: 'logOut',
  },
};
