export default {
  name: 'English',
  translation: {
    mainPage: 'Main page',
    graphiql: 'Graphiql',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    variables: 'Variables',
    headers: 'Headers',
    PleaseEnterName: 'Please enter name',
    FullName: 'Full Name',
    EmailAddress: 'E-mail Address',
    Password: 'Password',
    Register: 'Register',
    AlreadyHaveAnAccount: 'Already have an account?',
    Login: 'Login',
    SendPasswordResetEmail: 'Send password reset email',
    DontHave: 'Don`t have an account?',
    ForgotPassword: 'Forgot Password',
    ItsShort: 'It is too short',
    ItEmpty: 'It can`t be empty',
    ItEmail: 'It isn`t E-mail',
    longer: 'The password must be 8 or more characters long',
    NeedCapital: 'Need at least one capital letter',
    NeedSpecial: 'The password must contain numbers and a special character',
    NotRegister: 'This e-mail is`n register yet',
    inputFields: 'Input Fields',
    arguments: 'Arguments',
    type: 'Type',
    rootTypes: 'Root Types',
    fields: 'Fields',
    search: 'Search',
    endpoint: 'API endpoint',
    docsUnavailible: 'Documentation unavalible. Check api endpoint: {{- endpoint}}',
    tooltips: {
      logout: 'Logout',
      language: 'Choose language',
      docsOpen: 'Open documentation explorer',
      docsClose: 'Close documentation explorer',
      execute: 'Execute query',
      hideEditors: 'Hide editors',
      showEditors: 'Show editors',
      changeEndpoint: 'Change API',
      save: 'Save',
      home: 'Docs main page',
    },
    errors: {
      jsonVariables: 'Variables are invalid JSON: {{- message}}',
      httpStatusCodeError: 'Loading error occured (code: {{status}})',
      httpInvalidContentType: 'Invalid content-type in response',
      'Failed to fetch': 'Failed to fetch',
      'auth/email-already-in-use': 'Authorization error. Email already in use',
      'auth/wrong-password': 'Wrong password!',
      'auth/user-not-found': 'User not found!',
    },
  },
};
